name: RedBeat CI

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        exclude:
          - os: windows-latest
            python-version: '3.7'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run unittests
      run: py.test tests --cov=redbeat

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip', 'flake8'
      - name: Install dependencies
        run: |
          pip install flake8 flake8-black flake8-isort
      - name: Run linter
        run: flake8 --count --statistics .
